AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  DynamoAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
      Roles:
        - !Ref DynamoAccessRole
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref DynamoAccessRole
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0e7f241a967f9b30e"
      InstanceType: "t2.micro"
      KeyName: !Sub "jenkins"
      AvailabilityZone: !Sub "${AWS::Region}b"
      Tenancy: "default"
      SubnetId: "subnet-063dd014d61e4043d"
      EbsOptimized: false
      IamInstanceProfile: !Ref RootInstanceProfile
      SecurityGroupIds:
        - "sg-0621e7c6a29ec7922"
      SourceDestCheck: true
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            VolumeSize: 8
            SnapshotId: "snap-0c111f01135b959e0"
            VolumeType: "gp2"
            DeleteOnTermination: true
      UserData:
        Fn::Base64: |
          #!/bin/sh
          cd /home/ubuntu/node-server
          pm2 start index.js -f --name node-server
      Tags:
        - Key: "Name"
          Value: "node_server3"
      HibernationOptions:
        Configured: false
